# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  #push:
  #workflow_dispatch:
  pull_request:
    branches:
    - master
    - scm/*

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      # Set up Flutter.
      - name: Clone Flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor -v

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get

      # Analyze, check formatting, and run unit tests.
      - name: Ensure the Dart code is formatted correctly
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run Flutter unit tests
        run: flutter test
