# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  
  workflow_dispatch:
  
  pull_request:
    branches:
    - master
    - scm/*

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      # Set up Flutter.
      - name: Clone Flutter 
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'
      - run: flutter doctor -v

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed --dry-run .
      - name: Run Flutter unit tests
        run: flutter test
